# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e8ab36bf3400d1970bca618ed14adb2f98d05727bdfcf18a5a4d02b4bbcedc0636ba940a80ced4a5de311168d91332da2f1da862c1f0fe9a9665d854996bf8

test:
  secret_key_base: 1cfaf6e83b05a68847a97d7b923c23cf7628a76ce50aed210031bcfad9b5f34df6b8939bd613011cf80aca71fae0a87af346c847ddb81115f9152670d43dbc70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
